add Controls.DomainServices services to OS Ria solution
cshtml5/OpenRiaServices pull request #21
Opened 2022-04-28 14:39 UTC by ahmed-salem-me

I've also changed versions in nuget.spec so that it's not created in different root folder under nuget packages folder
instead we can have, 
C:\Users\user\.nuget\packages\opensilver.openriaservices.client
                                                                                                      \5.00
                                                                                                      \4.6

2022-09-23 16:51 UTC, barjonp requested changes
Can you delete the `BinaryTypeUtility.cs`, `ExceptionHandlingUtility.cs` and `TypeUtility.cs` files. We can just add the file as references to the csproj instead of duplicating them. (you can copy from line 29 to line 39 of this file: https://github.com/OpenSilver/OpenRiaServices/blob/support/4.6/OpenRiaServices.Controls.DomainServices/Framework/OpenRiaServices.Controls.DomainServices.csproj#L29).

2022-09-23 16:51 UTC, barjonp commented on OpenRiaServices.NuGet/OpenSilver/OpenRiaServices.OpenSilver.Client.Core.nuspec
> +    <id>OpenSilver.OpenRiaServices.Client.Core</id>
We need to keep 4.6 at the end as we are maintaining 2 OpenRia packages. One based on version 5 of OpenRia (the id of the NuGet package is OpenSilver.OpenRiaServices.Client.Core) and one based on the version 4.6 for Silverlight compatibility (NuGet package is OpenSilver.OpenRiaServices.Client.Core.4.6)
```suggestion
    <id>OpenSilver.OpenRiaServices.Client.Core.4.6</id>
```

2022-09-23 16:51 UTC, barjonp commented on OpenRiaServices.NuGet/OpenSilver/OpenRiaServices.OpenSilver.Client.nuspec
> +    <id>OpenSilver.OpenRiaServices.Client</id>
```suggestion
    <id>OpenSilver.OpenRiaServices.Client.4.6</id>
```

2022-09-23 16:51 UTC, barjonp commented on OpenRiaServices.NuGet/OpenSilver/OpenRiaServices.OpenSilver.Client.nuspec
> +        <dependency id="OpenSilver.OpenRiaServices.Client.Core" version="$PackageVersion$"/>
```suggestion
        <dependency id="OpenSilver.OpenRiaServices.Client.Core.4.6" version="$PackageVersion$"/>
```

2022-09-23 16:51 UTC, barjonp commented on OpenRiaServices.NuGet/OpenSilver/OpenSilver.OpenRiaServices.DomainDataSource.nuspec
> +    <id>OpenSilver.OpenRiaServices.DomainDataSource</id>
```suggestion
    <id>OpenSilver.OpenRiaServices.DomainDataSource.4.6</id>
```

2022-09-23 16:51 UTC, barjonp commented on OpenRiaServices.NuGet/OpenSilver/OpenSilver.OpenRiaServices.DomainDataSource.nuspec
> +        <dependency id="OpenSilver.OpenRiaServices.Client.Core"  version="$PackageVersion$"/>
```suggestion
        <dependency id="OpenSilver.OpenRiaServices.Client.Core.4.6"  version="$PackageVersion$"/>
```

2022-10-12 13:10 UTC, ahmed-salem-me commented
@barjonp I've made the required changes

2022-10-13 07:57 UTC, merged